/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.problemsolving.geektrust.familytree;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;

import static com.problemsolving.geektrust.familytree.Gender.FEMALE;
import static com.problemsolving.geektrust.familytree.Gender.MALE;
import static com.problemsolving.geektrust.familytree.MiscUtils.getInput;
import static java.util.Objects.requireNonNull;

public class PlanetLengaburu {
    public static final String FILE_PATH_AS_FIRST_ARGUMENT = "Pass in the file path as first argument.";
    public static final String MISSING_COMMANDS = "Missing commands.";
    static Logger LOGGER = LoggerFactory.getLogger(PlanetLengaburu.class.getSimpleName());
    private FamilyTree lengaburuFamily;

    public static void main(String[] args) throws Exception {
        requireNonNull(args, FILE_PATH_AS_FIRST_ARGUMENT);
        requireNonNull(args[0], FILE_PATH_AS_FIRST_ARGUMENT);
        new PlanetLengaburu().startFromFilePath(args[0]);
    }

    public String startFromFilePath(String inputFilePath) throws Exception {
        return startFromListOfArgs(getInput(inputFilePath));
    }

    public String startFromListOfArgs(List<String> inputs) throws Exception {
        requireNonNull(inputs, MISSING_COMMANDS);
        if (inputs.size() == 0) {
            throw new Exception(MISSING_COMMANDS);
        } else {
            init();
            processCommands();
        }
        return null;
    }

    private void processCommands() {

    }

    private void init() {
        lengaburuFamily = new FamilyTree("King Shan", "Queen Anga", MALE);
        // Level 01
        String kingShan = lengaburuFamily.getRootMember().getMember();
        lengaburuFamily.addMember(kingShan, "Chit", "Amba", MALE);
        lengaburuFamily.addMember(kingShan, "Ish", MALE);
        lengaburuFamily.addMember(kingShan, "Vich", "Lika", MALE);
        lengaburuFamily.addMember(kingShan, "Aras", "Chitra", MALE);
        lengaburuFamily.addMember(kingShan, "Satya", "Vyan", MALE);
        // Level 02
        lengaburuFamily.addMember(kingShan, "Satya", "Vyan", MALE);

    }

    private void addMembers() {
        // King Shan / Queen Anga
    }

}
